package com.thinkgem.jeesite.modules.video_m_n.dao;

import com.thinkgem.jeesite.modules.video_m_n.entity.MusicTable;

public interface MusicTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int insert(MusicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int insertSelective(MusicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    MusicTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int updateByPrimaryKeySelective(MusicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int updateByPrimaryKey(MusicTable record);
}