package com.thinkgem.jeesite.modules.video_m_n.dao;

import com.thinkgem.jeesite.modules.video_m_n.entity.NovelTableCount;

public interface NovelTableCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int insert(NovelTableCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int insertSelective(NovelTableCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    NovelTableCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int updateByPrimaryKeySelective(NovelTableCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int updateByPrimaryKey(NovelTableCount record);
}