package com.thinkgem.jeesite.modules.video_m_n.dao;

import com.thinkgem.jeesite.modules.video_m_n.entity.NovelTable;

public interface NovelTableMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int insert(NovelTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int insertSelective(NovelTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    NovelTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int updateByPrimaryKeySelective(NovelTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel_table
     *
     * @mbggenerated Sun Nov 27 22:59:49 CST 2016
     */
    int updateByPrimaryKey(NovelTable record);
}