package com.thinkgem.jeesite.modules.video_m_n.dao;

import com.thinkgem.jeesite.modules.video_m_n.entity.VideoTable;

public interface VideoTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_table
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_table
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int insert(VideoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_table
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int insertSelective(VideoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_table
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    VideoTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_table
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int updateByPrimaryKeySelective(VideoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_table
     *
     * @mbggenerated Mon Nov 28 15:12:20 CST 2016
     */
    int updateByPrimaryKey(VideoTable record);
}